name: Post Tag

# This workflow contains our release automation.
on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  release-build:
    name: Release Build (macos-latest)
    runs-on: macos-latest
    permissions:
      contents: read
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.0.app"
      SWIFT_VERSION: 6.2.3
    steps:
      - name: Select Xcode version
        run: |
          sudo xcode-select --switch "${DEVELOPER_DIR}/Contents/Developer"
          xcodebuild -version
      - name: Show Swift version
        run: swift --version
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: Install jemalloc
        run: brew install jemalloc
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build
        run: make build

  gh-release-notes:
    name: Release Notes
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Needed to create/update GH release.
    steps:
      - name: Set TAG_NAME in Environment
        # Subsequent jobs will be have the computed tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: Create or Update Release
        env:
          # Required for the GitHub CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./tools/build/github-release.sh --tag=${TAG_NAME}
